### ISSUE TITLE
BioLogic driver -- python 3

### ISSUE THREAD

**Issue by rduke199** [CINF/PyExpLabSys#45]
Are there plans to update the BioLogic driver to Python 3? My lab recently purchased an SP-50e poteniostat with plans to operate it via the this PyExpLabSys API. However, the antiquated python 2 dependencies render it nearly impossible to use with our existing workflow management and data processing codes.

**Comment by KennethNielsen** [comment]
Hallo @rduke199 

Not really, unfortunately. This driver never found any users in our lab, so there isn't much of a push on its development. Furthermore, I no longer have access to a test machine.

I am willing to help however, possibly reviewing a PR or the likes.

I did a quick test just of basically that I can run the module (meaning the imports check out and the syntax is valid) and the only problem I found there is that the ctypes.WinDLL was renamed to ctypes.windll in Python. You can try out the version in this pastebin and see if it works for you: https://pastebin.mozilla.org/QN0SAZ7U

Regards Kenneth

**Comment by rduke199** [comment]
Thanks for your response. But I decided not to use the BioLogic driver. I am building up my own code around the pared down api that comes with the potentiostat developer package.

**Comment by afischer-sweepme** [comment]
@rduke199 Could you please contact me via email (contact{at}sweep-me.net). I cannot DM here and would like to discuss something with you. Thanks!
