### ISSUE TITLE
installing PyExpLabSys package -- Python 3

### ISSUE THREAD

**Issue by Omaruccio** [CINF/PyExpLabSys#46]
Don't understand how to install PyExpLabSys package. I need to use the XGS-600 module to read pressure from the gauge controller.
Using pip install PyExpLabSys is not working.
Any solutions?

**Comment by hamid91hh** [comment]
I have the same problem. 
pip install PyExpLabSys doesn't work! Also, I didn't succeed to install the PyExpLabSys package manually.
I would be grateful if somebody could suggest an alternative solution or fix this issue.

**Comment by KennethNielsen** [comment]
I don't think we ever got around to pushing it up to PyPI. However, most of the drivers depend only on the rest of the package for a no-op marker of python version, so in the mean time, you could just copy the file that contains the driver over to your codebase and delete these two lines:
```python
from PyExpLabSys.common.supported_versions import python2_and_3
python2_and_3(__file__)
```

**Comment by Omaruccio** [comment]
Great. Thank you for your help!

**Comment by KennethNielsen** [comment]
No problem. I will close this issue and create one for packaging.
