### ISSUE TITLE
Semantic versioning vs. calendar versioning

### ISSUE THREAD

**Issue by KennethNielsen** [CINF/PyExpLabSys#53]
Before we start on releasing PyExpLabSys packages, we need to agree on a versioning system.

The two usual contenders for this are [semantic versioning](https://semver.org/) and [calendar versioning](https://calver.org/).

Main differences here are that SemVer applies special rules to when numbers change WRT to stable public API, backwards compatible and incompatible changes, bug fixes etc. etc. Traditionally it was viewed as an advantage that you could infer certain rules from this i.e. that it would always be safe to upgrade a minor version or similar. But also, almost traditionally, SemVer is difficult to manage. You need a firm grip on what goes on to make sure to increment the numbers right etc. which means that there is the risk of communicating information about e.g safe minor version upgrades which is just not correct.

As a result of this, CalVer was introduced into a some prominent projects, where the idea is simply, let's version according to calendar. You will the immediately know when the version was released, and how much work in the between two versions, but information about breaking changes ad safe upgrades will have to be kept elsewhere.

For me the vote is simple. Recognizing PyExpLabSys' origins, as a shared project in a research department, where it is sought to encourage non-programmer PhD-students to participate, I think it is unrealistic and counter productive to imagine incurring the kind of control that would be required for SemVer.

For this reason, I suggest a versioning scheme, which is simply the 0-padded date, like so::
**YYYY.0M.0D**
I thinks for all intents and purposes this should be sufficient, since I consider it unlikely that we will ever make a bug-fix release on the same day as the last release.

Making it pure date based also especially for PyExpLabSys means that we can safely communicate that we make **zero** promises about backwards compatibility.

What do you think?

**Comment by robertjensen** [comment]
Agree completely, keep it a date and avoid to promise anything :-D

**Comment by SIGithubUser** [comment]
@Ejler what do you think?

**Comment by KennethNielsen** [comment]
@Ejler what do you think

**Comment by Ejler** [comment]
I also think CalVer is the better fit for PyExpLabSys :)

**Comment by KennethNielsen** [comment]
CalVer it is
